"""Single source for Athena/Scout version metadata."""
ATHENA_VERSION = "0.6.4.1.0"
SCOUT_VERSION = "v0.6.4.1.0"
ATHENA_BUILD = "0.6.4.1.0"
RELEASE_NAME = "Adaptive Investigation Runtime Integration"
RELEASE_EPIC = "6"
RELEASE_SPRINT = "4"
RELEASE_PATCH = "1"
RELEASE_HOTFIX = "0"
VERSION_SCHEMA = "major.epic.sprint.patch.hotfix"
REPOSITORY_NAME = "AthenaEngine"
PYTHON_PACKAGE_NAME = "Athena"
VERSION = ATHENA_VERSION
ENGINE_LABEL = f"Athena v{ATHENA_VERSION}"
SCOUT_LABEL = f"Scout {SCOUT_VERSION}"
