"""Single source for Athena/Scout version metadata."""
ATHENA_VERSION = "0.6.5.11.1"
SCOUT_VERSION = "v0.6.5.11.1"
ATHENA_BUILD = "0.6.5.11.1"
RELEASE_NAME = "Application Path Ownership Correction"
RELEASE_EPIC = "6"
RELEASE_SPRINT = "5"
RELEASE_PATCH = "11"
RELEASE_HOTFIX = "1"
VERSION_SCHEMA = "major.epic.sprint.patch.hotfix"
REPOSITORY_NAME = "AthenaEngine"
PYTHON_PACKAGE_NAME = "Athena"
VERSION = ATHENA_VERSION
ENGINE_LABEL = f"Athena v{ATHENA_VERSION}"
SCOUT_LABEL = f"Scout {SCOUT_VERSION}"
