"""Single source for Athena/Scout version metadata."""
ATHENA_VERSION = "0.6.5.10.7"
SCOUT_VERSION = "v0.6.5.10.7"
ATHENA_BUILD = "0.6.5.10.7"
RELEASE_NAME = "Canonical Player Statistical Evidence"
RELEASE_EPIC = "6"
RELEASE_SPRINT = "5"
RELEASE_PATCH = "10"
RELEASE_HOTFIX = "7"
VERSION_SCHEMA = "major.epic.sprint.patch.hotfix"
REPOSITORY_NAME = "AthenaEngine"
PYTHON_PACKAGE_NAME = "Athena"
VERSION = ATHENA_VERSION
ENGINE_LABEL = f"Athena v{ATHENA_VERSION}"
SCOUT_LABEL = f"Scout {SCOUT_VERSION}"
