"""Deterministic retrieval over compact public hockey knowledge packs.

Athena does not reason directly from NHL/NHLPA source PDFs at runtime. This
module retrieves bounded evidence from compact JSON knowledge packs generated by
``public_hockey_packs.py`` and returns evidence records that Scout can expose in
public-sports mode or fantasy mode.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple
import json
import re

try:
    from Core.version import ATHENA_VERSION
except Exception:  # pragma: no cover
    ATHENA_VERSION = "unknown"

try:
    from Knowledge.Sources.public_hockey_packs import build_public_hockey_knowledge_packs, load_public_hockey_pack_summary
except Exception:  # pragma: no cover
    build_public_hockey_knowledge_packs = None  # type: ignore
    load_public_hockey_pack_summary = None  # type: ignore


def _tokenize(value: str) -> List[str]:
    tokens = re.findall(r"[a-z0-9]+", str(value).lower())
    stopwords = {"a", "an", "and", "are", "as", "at", "be", "by", "can", "did", "do", "does", "for", "from", "how", "in", "is", "it", "of", "on", "or", "should", "the", "this", "to", "what", "when", "where", "who", "why", "with"}
    tokens = [token for token in tokens if len(token) > 2 and token not in stopwords]
    expanded: List[str] = []
    aliases = {
        "lti": ["ltir", "injured", "reserve"],
        "ltir": ["lti", "injured", "reserve", "playoff", "cap"],
        "ir": ["injured", "reserve", "injury"],
        "nmc": ["no", "move", "clause", "no", "trade"],
        "ntc": ["no", "trade", "clause"],
        "offside": ["off", "side", "offside"],
        "off": ["offside"],
        "waiver": ["waivers", "claim"],
        "waivers": ["waiver", "claim"],
        "cap": ["salary", "upper", "limit"],
        "contract": ["contracts", "term"],
        "contracts": ["contract", "term"],
    }
    for token in tokens:
        expanded.append(token)
        expanded.extend(aliases.get(token, []))
    # preserve order while deduplicating
    seen = set()
    result = []
    for token in expanded:
        if token and token not in seen:
            seen.add(token)
            result.append(token)
    return result


def _project_root(project_root: Optional[Path] = None) -> Path:
    return Path(project_root or Path.cwd())


def _load_json(path: Path, fallback: Any) -> Any:
    try:
        if path.exists():
            return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return fallback
    return fallback


def _pack_dirs_from_summary(root: Path) -> List[Path]:
    summary: Dict[str, Any] = {}
    if load_public_hockey_pack_summary is not None:
        try:
            summary = load_public_hockey_pack_summary(root) or {}
        except Exception:
            summary = {}
    dirs: List[Path] = []
    for pack in summary.get("packs", []) or []:
        candidate = Path(pack.get("pack_root", ""))
        if not candidate.is_absolute():
            candidate = root / candidate
        if candidate.exists():
            dirs.append(candidate)
    if dirs:
        return dirs

    fallback_roots = [
        root / "Knowledge" / "Packs" / "NHL" / "rulebook" / "2025_2026",
        root / "Knowledge" / "Packs" / "NHL" / "cba" / "2025_mou",
    ]
    return [path for path in fallback_roots if path.exists()]


def ensure_public_hockey_packs(project_root: Optional[Path] = None) -> Dict[str, Any]:
    """Ensure compact public hockey packs exist and return their summary/status."""
    root = _project_root(project_root)
    if build_public_hockey_knowledge_packs is not None:
        try:
            return build_public_hockey_knowledge_packs(root)
        except Exception as exc:
            return {
                "athena_version": ATHENA_VERSION,
                "knowledge_domain": "public_hockey",
                "status": "error",
                "error": str(exc),
                "pack_count": 0,
                "packs_present": 0,
                "document_backed_packs": 0,
                "packs": [],
            }
    return {"athena_version": ATHENA_VERSION, "status": "unavailable", "packs": []}


def load_public_hockey_packs(project_root: Optional[Path] = None, auto_build: bool = False) -> List[Dict[str, Any]]:
    """Load all compact public hockey packs from ``Knowledge/Packs``."""
    root = _project_root(project_root)
    if auto_build and not _pack_dirs_from_summary(root):
        ensure_public_hockey_packs(root)

    packs: List[Dict[str, Any]] = []
    for pack_dir in _pack_dirs_from_summary(root):
        manifest = _load_json(pack_dir / "manifest.json", {})
        topic_index = _load_json(pack_dir / "topic_index.json", {})
        body_filename = "rules.json" if (pack_dir / "rules.json").exists() else "provisions.json" if (pack_dir / "provisions.json").exists() else "entries.json"
        entries = _load_json(pack_dir / body_filename, [])
        if manifest:
            packs.append({
                "pack_root": str(pack_dir),
                "manifest": manifest,
                "body_filename": body_filename,
                "entries": entries if isinstance(entries, list) else [],
                "topic_index": topic_index if isinstance(topic_index, dict) else {},
            })
    return packs


def _entry_text(entry: Dict[str, Any]) -> str:
    values: List[str] = []
    for key in ("topic_key", "label", "category", "notes", "source_title", "authority"):
        values.append(str(entry.get(key, "")))
    values.extend(str(v) for v in entry.get("keywords", []) or [])
    values.extend(str(v) for v in entry.get("authority_refs", []) or [])
    return " ".join(values).lower()


def _score_entry(query_tokens: Sequence[str], entry: Dict[str, Any], topic_index: Dict[str, Any]) -> Tuple[int, List[str]]:
    matched: List[str] = []
    score = 0
    topic_key = entry.get("topic_key")
    text = _entry_text(entry)
    for token in query_tokens:
        indexed_topic_keys = topic_index.get(token, []) or []
        if topic_key in indexed_topic_keys:
            score += 5
            matched.append(token)
        elif re.search(r"\b" + re.escape(token) + r"\b", text):
            score += 2
            matched.append(token)
    # Direct exact key/label boost.
    query_phrase = " ".join(query_tokens)
    if entry.get("topic_key") and str(entry["topic_key"]).replace("_", " ") in query_phrase:
        score += 4
    if entry.get("label") and str(entry["label"]).lower() in query_phrase:
        score += 4
    return score, sorted(set(matched))


_TOPIC_SUMMARIES: Dict[str, str] = {
    "playing_area": "Covers rink dimensions, markings, boards/glass, goal crease, and other playing-area requirements.",
    "eligible_players": "Covers eligible/ineligible players, submitted lineups, player participation, and game-roster constraints.",
    "injured_players": "Covers on-ice injured-player handling, injured goalkeepers, substitution requirements, and visible blood/equipment issues.",
    "penalty_types": "Covers minor, bench-minor, double-minor, major, match, misconduct, delayed-penalty, and short-handed penalty mechanics.",
    "video_review": "Covers video review and coach's challenge authority in the NHL rulebook.",
    "game_flow": "Covers game-flow rules including face-offs, goals, icing, off-side, overtime, line changes, and puck-out-of-bounds situations.",
    "salary_cap": "Covers CBA/MOU economic rules related to cap setting, upper-limit concepts, escrow, and Hockey Related Revenue mechanics.",
    "ltir_lti": "Covers MOU provisions related to LTI/LTIR and playoff cap counting. Use this as source evidence for cap-treatment questions, not as a full cap calculator.",
    "minimum_salary": "Covers NHL minimum-salary provisions referenced by the MOU.",
    "performance_bonus_injured_veterans": "Covers performance-bonus eligibility concepts for injured veteran players.",
    "no_trade_lists": "Covers filing of no-trade lists and related contract-clause process references.",
    "salary_retention": "Covers MOU provisions related to retained salary and second retained salary transactions.",
    "contract_variability": "Covers contract salary-variability restrictions referenced by the MOU.",
    "contract_term_limits": "Covers contract term limitations and extension/sign-and-trade concepts referenced by the MOU.",
    "four_recall_rule": "Covers CBA/MOU roster recall limits and emergency/active-roster recall concepts.",
    "waiver_system_access": "Covers MOU provisions related to NHLPA access to the waiver system. This is not a full waiver-eligibility calculator by itself.",
    "supplementary_discipline": "Covers supplementary discipline, fine, suspension, and maximum-fine concepts referenced by the MOU.",
}


def _evidence_record(pack: Dict[str, Any], entry: Dict[str, Any], score: int, matched_terms: Sequence[str]) -> Dict[str, Any]:
    manifest = pack.get("manifest", {})
    pack_root = Path(pack.get("pack_root", ""))
    topic_key = entry.get("topic_key")
    return {
        "source_id": manifest.get("source_id") or entry.get("source_id"),
        "source_title": manifest.get("title") or entry.get("source_title"),
        "authority": manifest.get("authority") or entry.get("authority"),
        "document_type": manifest.get("document_type"),
        "season": manifest.get("season"),
        "effective_date": manifest.get("effective_date"),
        "pack_root": str(pack_root),
        "body_file": str(pack_root / pack.get("body_filename", "")),
        "topic_key": topic_key,
        "label": entry.get("label"),
        "category": entry.get("category"),
        "authority_refs": list(entry.get("authority_refs", []) or []),
        "keywords": list(entry.get("keywords", []) or []),
        "summary": _TOPIC_SUMMARIES.get(str(topic_key), entry.get("notes") or "Registered public hockey knowledge topic."),
        "matched_terms": list(matched_terms),
        "score": score,
        "citation_policy": manifest.get("citation_policy") or entry.get("citation_policy"),
        "source_document_present": bool((manifest.get("source_document") or {}).get("present")),
    }


def retrieve_public_hockey_knowledge(
    query: str,
    project_root: Optional[Path] = None,
    mode: str = "public_sports",
    limit: int = 5,
    auto_build: bool = False,
) -> Dict[str, Any]:
    """Retrieve deterministic public hockey evidence for a question/topic.

    The function returns evidence only from compact knowledge packs. It never
    invents facts and does not read source PDFs directly at runtime.
    """
    root = _project_root(project_root)
    query = str(query or "").strip()
    query_tokens = _tokenize(query)
    packs = load_public_hockey_packs(root, auto_build=auto_build)
    candidates: List[Dict[str, Any]] = []

    for pack in packs:
        manifest = pack.get("manifest", {})
        modes = set(manifest.get("modes", []) or [])
        if mode and modes and mode not in modes:
            continue
        topic_index = pack.get("topic_index", {})
        for entry in pack.get("entries", []) or []:
            score, matched_terms = _score_entry(query_tokens, entry, topic_index)
            if score > 0:
                candidates.append(_evidence_record(pack, entry, score, matched_terms))

    candidates.sort(key=lambda item: (-int(item.get("score", 0)), str(item.get("source_id", "")), str(item.get("topic_key", ""))))
    evidence = candidates[: max(1, int(limit or 5))]
    status = "available" if evidence else "no_match" if packs else "missing_packs"
    confidence = 0.0
    if evidence:
        best = max(item.get("score", 0) for item in evidence)
        confidence = min(0.9, 0.45 + (float(best) / 20.0))
    elif packs:
        confidence = 0.25
    else:
        confidence = 0.1

    limitations: List[str] = []
    if not packs:
        limitations.append("Public hockey knowledge packs are not built. Run Tools/build_public_hockey_knowledge_packs.py.")
    if not evidence:
        limitations.append("No compact public hockey knowledge-pack topic matched the question.")
    limitations.append("This retrieval layer returns source/topic evidence only; full legal/cap calculations require dedicated intelligence modules.")

    return {
        "athena_version": ATHENA_VERSION,
        "knowledge_domain": "public_hockey",
        "query": query,
        "mode": mode,
        "status": status,
        "confidence": round(confidence, 3),
        "packs_checked": len(packs),
        "evidence_count": len(evidence),
        "evidence": evidence,
        "limitations": limitations,
    }


def build_public_hockey_scout_answer(
    question: str,
    project_root: Optional[Path] = None,
    mode: str = "public_sports",
) -> Dict[str, Any]:
    """Build a bounded Scout-style answer from retrieved knowledge-pack evidence."""
    retrieval = retrieve_public_hockey_knowledge(question, project_root=project_root, mode=mode, limit=5, auto_build=False)
    evidence = retrieval.get("evidence", [])
    if evidence:
        labels = ", ".join(f"{item['label']} ({'; '.join(item.get('authority_refs', []) or [])})" for item in evidence[:3])
        conclusion = f"Athena found public hockey knowledge-pack evidence relevant to this question: {labels}."
        observed = [
            f"{item['label']}: {item['summary']} Source: {item['source_title']} — {('; '.join(item.get('authority_refs', []) or ['registered topic']))}."
            for item in evidence[:5]
        ]
        title = "Public hockey knowledge"
    else:
        conclusion = "Athena could not find a matching public hockey knowledge-pack topic for this question."
        observed = [f"Packs checked: {retrieval.get('packs_checked', 0)}."]
        title = "Public hockey knowledge unavailable"

    return {
        "title": title,
        "confidence": retrieval.get("confidence", 0.0),
        "conclusion": conclusion,
        "observed_facts": observed,
        "known_limitations": retrieval.get("limitations", []),
        "developer_trace": {
            "question": question,
            "mode": mode,
            "retrieval_status": retrieval.get("status"),
            "packs_checked": retrieval.get("packs_checked"),
            "evidence_used": evidence,
        },
    }


def write_public_hockey_retrieval_report(
    query: str,
    project_root: Optional[Path] = None,
    mode: str = "public_sports",
) -> Dict[str, str]:
    """Write JSON/TXT retrieval outputs for debugging."""
    root = _project_root(project_root)
    retrieval = retrieve_public_hockey_knowledge(query, root, mode=mode, limit=10, auto_build=False)
    output_dir = root / "Output"
    reports_dir = root / "Reports"
    output_dir.mkdir(parents=True, exist_ok=True)
    reports_dir.mkdir(parents=True, exist_ok=True)
    slug = re.sub(r"[^a-z0-9]+", "_", query.lower()).strip("_")[:60] or "query"
    json_path = output_dir / f"public_hockey_retrieval_{slug}.json"
    txt_path = reports_dir / f"public_hockey_retrieval_{slug}.txt"
    json_path.write_text(json.dumps(retrieval, indent=2, ensure_ascii=False), encoding="utf-8")

    lines = [
        "Public Hockey Knowledge Retrieval",
        "=================================",
        f"Athena: {retrieval['athena_version']}",
        f"Query: {retrieval['query']}",
        f"Mode: {retrieval['mode']}",
        f"Status: {retrieval['status']}",
        f"Confidence: {retrieval['confidence']}",
        f"Evidence: {retrieval['evidence_count']}",
        "",
    ]
    for item in retrieval.get("evidence", []):
        lines.append(f"- {item['label']} [{item['topic_key']}]")
        lines.append(f"  Source: {item['source_title']}")
        lines.append(f"  Authority refs: {'; '.join(item.get('authority_refs', []) or [])}")
        lines.append(f"  Summary: {item['summary']}")
        lines.append("")
    if retrieval.get("limitations"):
        lines.append("Limitations")
        lines.append("-----------")
        for limitation in retrieval["limitations"]:
            lines.append(f"- {limitation}")
    txt_path.write_text("\n".join(lines), encoding="utf-8")
    return {"json": str(json_path), "text": str(txt_path)}


if __name__ == "__main__":  # pragma: no cover
    print(json.dumps(retrieve_public_hockey_knowledge("LTIR waivers icing", Path.cwd()), indent=2, ensure_ascii=False))
